### ISSUE TITLE
Upgrade to react-styleguidist 5.x

### ISSUE THREAD

**Issue by okonet** [styleguidist/snapguidist#13]
Now that 5.x is out, this package still requires 4.5 of react-styleguidist

```
"react-styleguidist": ">=4.5 <5",
```

It would be great to get a new version that is compatible with 5.x

**Comment by cef62** [comment]
You are totally right, we a 5.x compatible version is under development.

**Comment by cef62** [comment]
Maybe we should add a note on the main readme until the new version is ready, what do you think @MicheleBertoli?

**Comment by MicheleBertoli** [comment]
Absolutely, as soon as we publish a branch for v5 we can link it in the README.

**Comment by cloud-walker** [comment]
Any news on this topic?

**Comment by sapegin** [comment]
The very basic plugin API in Styleguidist is kinda close so we should start moving Snapguidist to it but I need your help here because I don’t know what Snapguidist needs from Styleguidist.

**Comment by MicheleBertoli** [comment]
I'm so sorry but I've been incredibly busy in the last few months (and @cef62 as well).
We'll do our best to get back on track asap, and any help from the community is highly appreciated.
Thanks!

**Comment by MicheleBertoli** [comment]
Hello everyone!
I had some free time during the weekend, and I tried to make the minimum amount of [changes](https://github.com/styleguidist/snapguidist/compare/v5?expand=1) to the package in order to support v5.
It's not optimal but I guess it's OK for now as far as it works, and it does work with the local example as you can see here:

![rsg](https://user-images.githubusercontent.com/1308971/27008844-b5462622-4e75-11e7-9557-96e8831e0baa.gif)

However, I haven't been able to make it work with the `react-styleguidist`'s basic example because it gives me the following errors:

```sh
Failed to compile.

Error in multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css
Module not found: Can't resolve 'style' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css

Error in ./~/react-styleguidist/lib/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'babel' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css

Error in ./~/react-styleguidist/lib/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'babel' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css
```

If you want to try it: `yarn add snapguidist@next`.

**Comment by MicheleBertoli** [comment]
Hello everyone!
I had some free time during the weekend, and I tried to make the minimum amount of [changes](https://github.com/styleguidist/snapguidist/compare/v5?expand=1) to the package in order to support v5.
It's not optimal but I guess it's OK for now as long as it works, and it does work with the local example as you can see here:

![rsg](https://user-images.githubusercontent.com/1308971/27008844-b5462622-4e75-11e7-9557-96e8831e0baa.gif)

However, I haven't been able to make it work with the `react-styleguidist`'s basic example because it gives me the following errors:

```sh
Failed to compile.

Error in multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css
Module not found: Can't resolve 'style' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css

Error in ./~/react-styleguidist/lib/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'babel' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css

Error in ./~/react-styleguidist/lib/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'babel' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css
```

If you want to try it: `yarn add snapguidist@next`.

**Comment by MicheleBertoli** [comment]
Hello everyone!
I had some free time during the weekend, and I tried to make the minimum amount of [changes](https://github.com/styleguidist/snapguidist/compare/v5?expand=1) to the package in order to support v5.
It's not optimal but I guess it's OK for now as long as it works, and it does work with the local example as you can see here:

![rsg](https://user-images.githubusercontent.com/1308971/27008844-b5462622-4e75-11e7-9557-96e8831e0baa.gif)

However, I haven't been able to make it work with the `react-styleguidist`'s basic example because it gives me the following errors:

```sh
Failed to compile.

Error in multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css
Module not found: Can't resolve 'style' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css

Error in ./~/react-styleguidist/lib/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'babel' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css

Error in ./~/react-styleguidist/lib/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'babel' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css
```

Repro steps:

- `git clone https://github.com/styleguidist/react-styleguidist.git`
- `cd react-styleguidist/examples/basic`
- `yarn add snapguidist@next`.
- apply the following changes to `styleguide.config.js`
```diff
@@ -1,5 +1,6 @@
+const snapguidist = require('snapguidist');
 const loaders = require('loaders');
-module.exports = {
+module.exports = snapguidist({
        components: 'src/components/**/[A-Z]*.js',
        defaultExample: true,
        webpackConfig: {
@@ -7,4 +8,4 @@ module.exports = {
                        loaders: loaders.all,
                },
        },
-};
+});
```
- `yarn styleguide`

**Comment by MicheleBertoli** [comment]
Hello everyone!
I had some free time during the weekend, and I tried to make the minimum amount of [changes](https://github.com/styleguidist/snapguidist/compare/v5?expand=1) to the package in order to support v5.
It works with the local example (`yarn start`) as you can see here:

![rsg](https://user-images.githubusercontent.com/1308971/27008844-b5462622-4e75-11e7-9557-96e8831e0baa.gif)

However, I haven't been able to make it work with the `react-styleguidist`'s basic example because it gives me the following errors:

```sh
Failed to compile.

Error in multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css
Module not found: Can't resolve 'style' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css

Error in ./~/react-styleguidist/lib/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'babel' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css

Error in ./~/react-styleguidist/lib/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'babel' in '/Users/michele/code/react-styleguidist/examples/basic'

 @ multi ./~/react-styleguidist/lib/index ./~/react-dev-utils/webpackHotDevClient.js ./~/snapguidist/src/styles.css
```

Repro steps:

- `git clone https://github.com/styleguidist/react-styleguidist.git`
- `cd react-styleguidist/examples/basic`
- `yarn add snapguidist@next`.
- apply the following changes to `styleguide.config.js`
```diff
@@ -1,5 +1,6 @@
+const snapguidist = require('snapguidist');
 const loaders = require('loaders');
-module.exports = {
+module.exports = snapguidist({
        components: 'src/components/**/[A-Z]*.js',
        defaultExample: true,
        webpackConfig: {
@@ -7,4 +8,4 @@ module.exports = {
                        loaders: loaders.all,
                },
        },
-};
+});
```
- `yarn styleguide`

**Comment by sapegin** [comment]
We don’t have babel-loader anymore, you should transpile files before publishing. In general don’t rely on any webpack loaders ;-) For styles it’s better to use JSS and Styled component the same way it’s done in Styleguidist itself.

**Comment by sapegin** [comment]
This guide may be useful too: https://react-styleguidist.js.org/docs/development.html

**Comment by sapegin** [comment]
@MicheleBertoli @cef62 Ping me when you’re ready to discuss how to make it a plugin ;-)

**Comment by MicheleBertoli** [comment]
> We don’t have babel-loader anymore

Yeah, but it's a dependency of Snapguidist so it should be there.
It turns out I was missing `-loader` :)
It works now.

This is more a quick win to support v5, but our goal is definitely to write a plugin. 
Thanks @sapegin.

**Comment by MicheleBertoli** [comment]
Anyone who wants to try the next version, please run:
`yarn add --dev snapguidist@next`
Feedback is highly appreciated.
